const types = {
  ARTICLESETTINGS : 'ARTICLE_SETTINGS_WINDOW',
  CHECKOUT        : 'CHECKOUT_WINDOW',
  LOGIN           : 'LOGIN_WINDOW',
  MARKDOWNPASTE   : 'MARKDOW_PASTE',
  PP              : 'PRIVACY_POLICY_WINDOW',
  PROGRESS        : 'PROGRESS_WINDOW',
  RECOVER         : 'RECOVER_PASSWORD_WINDOW',
  RESETPASSWORD   : 'RESET_PASSWORD_WINDOW',
  RETURN          : 'RETURN_POLICY_WINDOW',
  SIGNUP          : 'SIGNUP_WINDOW',
  SUBSCRIBE       : 'SUBSCRIBE_WINDOW',
  TOS             : 'TERMS_OF_SERVICE_WINDOW'
};

export default {...types};