/* @flow weak */

export default {
  ANNOTATION_SAVE: 'ANNOTATION_SAVE',
  ANNOTATION_DELETE: 'ANNOTATION_DELETE',
  CREATE_MARKER: 'CREATE_MARKER',
  PENDING_ANNOTATION_CREATION_MOVE: 'PENDING_ANNOTATION_CREATION_MOVE',
  MOVE_ANNOTATION: 'MOVE_ANNOTATION',
  PENDING_ANNOTATION_CREATION_START: 'PENDING_ANNOTATION_CREATION_START',
  PENDING_ANNOTATION_CREATION_END: 'PENDING_ANNOTATION_CREATION_END',
  SET_PENDING_ANNOTATION: 'SET_PENDING_ANNOTATION',
};
