/* @flow weak */

export default {
  IMAGE_ADDITION: 'IMAGE_ADDITION',
  CURRENT_IMAGE_DELETION: 'CURRENT_IMAGE_DELETION',
  SAVE_CURRENT_IMAGE: 'SAVE_CURRENT_IMAGE',
  CHANGE_CURRENT_IMAGE_INDEX: 'CHANGE_CURRENT_IMAGE_INDEX',
  IMAGE_MODIFICATION: 'IMAGE_MODIFICATION',
  IMAGE_ROTATION: 'IMAGE_ROTATION'
};
